#!/bin/bash

#check input file validation
if [ -z "$1" ]; then
	echo "Please use $0 <fileName.tsv"
	exit 1
fi

input_file="$1"

awk -F'\t' '
	NR == 1 {
                #find column indexes of Domains and Mechanics
		for ( i = 1; i <= NF; i++ ) {
			if ( tolower($i) == "domains" ) domains_col=i
			if ( tolower($i) == "mechanics" ) mechanics_col=i
		}

		if ( !domains_col ) {
			print "Error : Missing Domains column in the dataset"
		}
		if ( !mechanics_col ) {
			print "Error : Missing Mechanics column in the dataset"
		}
	}
' "$input_file"
