#!/bin/bash

#Author : Dulya Murage - 24910402

#check input file validation
if [ -z "$1" ]; then
	echo "Please use $0 <fileName.tsv"
	exit 1
fi

input_file="$1"

awk -F'\t' '
	NR == 1 {
                #find column indexes of Domains and Mechanics
		for ( i = 1; i <= NF; i++ ) {
			if ( tolower($i) == "domains" ) domains_col=i
			if ( tolower($i) == "mechanics" ) mechanics_col=i
		}

		#handle error in case the required columns are nor present in the dataset
		if ( !domains_col ) {
			print "Error : Missing Domains column in the dataset"
			exit 1
		}
		if ( !mechanics_col ) {
			print "Error : Missing Mechanics column in the dataset"
			exit 1
		}

		next

	}

	NR > 1 {
		#for each row after header, proces the data

		#split the 'Domains' column by (,) in to individual domains
		n = split($(domains_col),domains,",")

		for ( i = 1; i <= n; i++ ) {
			#check if the domain is not an empty string
			if ( domains[i] != "") {
				#trim leading/trailing spaces
				gsub(/^[ \t]+|[ \t]+$/, "", domains[i])  # Trim spaces
				#increment the count for each domain encountered
				domains_count[domains[i]]++
			}

		}

		#split the 'Mechanics' column by (,) in to individual mechanics
		m = split($(mechanics_col),mechanics,",")

		for ( i = 1; i <= m; i++ ) {
			#check is the mechnic is not an empty string
			if ( mechanics[i] != "") {
				#trim leading/trailing spaces
				gsub(/^[ \t]+|[ \t]+$/, "", mechanics[i])
				#increment the count for each mechanic encountered
				mechanics_count[mechanics[i]]++
			}
		}
	}

	END {
		#find most popular domain
		max_domain=""
		max_domain_count=0
		for ( d in domains_count ) {
			if ( domains_count[d] > max_domain_count ) {
				max_domain=d
				max_domain_count=domains_count[d]
			}
		}
		#find most popular mechanic
		max_mechanic=""
		max_mechanic_count=0
		for ( m in mechanics_count) {
			if ( mechanics_count[m] > max_mechanic_count) {
				max_mechanic =m
				max_mechanic_count=mechanics_count[m]
			}
		}
		printf("The most popular game mechanics is %s found in %d games\n", max_mechanic, max_mechanic_count)
		printf("The most game domian is %s found in %d games\n", max_domain, max_domain_count)
	}
' "$input_file"
