#!/bin/bash

#Author : Dulya Murage - 24910402

#check if the file name is provided
if [ -z "$1" ]; then
	echo "Please use $0 <fileName.txt>"
	exit 1
fi

tr -d '\r' < "$1" | awk -F';' '{
	#loop through each column field in the current line
	for (i = 1; i <= NF ; i++) {
		if (NR == 1) {
			#on the first line(header) initialize header array and store each column name
			header[i] = $i
			#initilize empty field counters array
			count[i] = 0
			max_col = NF
		} else if ($i == "") {
			#if a column cell is empty, increment the corresponding counter
			count[i]++
		}
	}
}
END {
	for (i = 1; i <= max_col; i++) {
		#print the number of empty cells per column
		print header[i] ": " count[i]
	}
}'
